export const DATA = {
    BRANDS: ['McDonald\'s', 'A&W', 'KFC'],
    FOODS: ['Fries', 'Burger'],
    PLATFORMS: [
        {id: 'Facebook', name: 'Facebook'},
        {id: 'Food Packaging', name: 'Food Packaging'},
        {id: 'Instagram', name: 'Instagram'},
        {id: 'Mobile app', name: 'Mobile app'},
        {id: 'Outdoor billboard', name: 'Outdoor billboard'},
        {id: 'Sign/Poster', name: 'Sign/Poster'},
        {id: 'Snapchat', name: 'Snapchat'},
        {id: 'Sponsorship (teams, events)', name: 'Sponsorship (teams, events)'},
        {id: 'Television', name: 'Television'},
        {id: 'TikTok', name: 'TikTok'},
        {id: 'Twitter', name: 'Twitter'},
        {id: 'Video Game', name: 'Video Game'},
        {id: 'Website', name: 'Website'},
        {id: 'YouTube', name: 'YouTube'},
        {id: 'Other', name: 'Other'}],
    INDICATORS: [
        {id: 'Celebrity', name: 'Celebrity'},
        {id: 'Character', name: 'Character'},
        {id: 'Humour', name: 'Humour'},
        {id: 'Language', name: 'Language'},
        {id: 'Music', name: 'Music'},
        {id: 'Teen actor', name: 'Teen actor'}],
    THEMES: [
        {name: '"Cool" or "Trendy"', id: '"Cool" or "Trendy"'},
        {name: 'Concert', id: 'Concert'},
        {name: 'Coupons', id: 'Coupons'},
        {name: 'Dance', id: 'Dance'},
        {name: 'Fashion', id: 'Fashion'},
        {name: 'Limited edition', id: 'Limited edition'},
        {name: 'Limited time offers', id: 'Limited time offers'},
        {name: 'Party', id: 'Party'},
        {name: 'School', id: 'School'},
        {name: 'Sexuality', id: 'Sexuality'},
        {name: 'Special offers', id: 'Special offers'},
        {name: 'Sports', id: 'Sports'},
        {name: 'Technology', id: 'Technology'}]
};